### ISSUE TITLE
Anzeige Bus

### ISSUE THREAD

**Issue by kay-cut** [nixnuex/MMM-SwissCommute#1]
Hi
Mache ich was falsch oder unterstütz das Plugin keine Bus-Verbindungen?
Habe diverses getestet leider ohne erfolg.

**Comment by nixnuex** [comment]
Fixed in https://github.com/nixnuex/MMM-SwissCommute/commit/a9ee1d2b96be6f07d2217e0872b576095ca9fc65

Jetzt sollten auch Busse funktionieren!
