### ISSUE TITLE
Full Stack IOS engineering job at fast traction startup

### ISSUE THREAD

**Issue by SwaminathaSwami** [nixnuex/MMM-SwissCommute#3]
Hi Nixnuex, 

I'm the CEO of Scope. I came across your profile and saw you attended make school, and it reminded me that we are actively hiring for talented engineers. I wanted to see if you'd be interested in working with us at Scope— if you're up for it, I'd love to have a phone call next week to chat. 

- Pranav Neyveli

**Comment by nixnuex** [comment]
Spam.

**Comment by SwaminathaSwami** [comment]
No man I am being genuine, sorry for reaching you here, I couldn't find anywhere else.
