### ISSUE TITLE
Display multiple MMM-SwissCommute modules beneath each other

### ISSUE THREAD

**Issue by mkubicek** [nixnuex/MMM-SwissCommute#4]
Hey nixnuex,

thanks for this awesome module!

Is there really a need for "display: inline-block;" in the css?
If multiple instances of the module are loaded they are displayed in the same row. Removing "display: inline-block;" seems to fix this issue.

Cheers,
m

**Comment by nixnuex** [comment]
Hi mkubicek
Thx for the feedback, glad that you enjoy the module! You are totally right, removing the `display: inline-block` allows multiple instances on the same position. Fixed in https://github.com/nixnuex/MMM-SwissCommute/commit/62762b98605f45a1768ede01f3db5adf2979a388.
