### ISSUE TITLE
Change icon depending on means of transportation

### ISSUE THREAD

**Issue by turnitclockwise** [nixnuex/MMM-SwissCommute#5]
Hi
First of all, thanks for this great module. It works perfectly as is.
I have a little request: Would it be possible to change the icon of the connection based on the type of vehicle (train, tram, bus)?

User @vanhoekd managed to do this in his module [MMM-SwissStationboard](https://github.com/vanhoekd/MMM-SwissStationboard/blob/master/MMM-SwissStationboard.js), which is based off your module.

Because I have little to zero experience with javascript and css, i couldn't make it work by just copy-pasting from his code into yours. In your [MMM-SwissCommute.js](https://github.com/nixnuex/MMM-SwissCommute/blob/master/MMM-SwissCommute.js) from line 107 onward, (i believe) you define/set the train icon and number

`// Number
			var trainNumberCell = document.createElement("td");
			trainNumberCell.innerHTML = "<i class=\"fa fa-train\"></i> " + trains.number;
			trainNumberCell.className = "align-left";
			row.appendChild(trainNumberCell);`

User @vanhoekd made some if-else statements to determine the icon in his [script](https://github.com/vanhoekd/MMM-SwissStationboard/blob/master/MMM-SwissStationboard.js) from line 148 onward:

`// Number
			var trainNumberCell = document.createElement("td");
			if (trains.type.localeCompare("bus")==0 || trains.type.localeCompare("post")==0){
				trainNumberCell.innerHTML = "<i class=\"fa fa-bus\"></i> " + trains.number;
			} else if(trains.type.localeCompare("tram")==0){
				trainNumberCell.innerHTML = "<i class=\"fa fa-subway\"></i> " + trains.number;
			}else if(trains.type.localeCompare("strain")==0 || trains.type.localeCompare("express_train")==0 || trains.type.localeCompare("train")==0){
				trainNumberCell.innerHTML = "<i class=\"fa fa-train\"></i> " + trains.number;
			}else{
				trainNumberCell.innerHTML = "<i class=\"fa fa-rocket\"></i> " + trains.number;
			}`

Although the code looks very similar, when i copied his code into your script, the connections wouldn't load anymore on the mirror. Any idea how i could fix this?

Thanks in advance!

**Comment by nixnuex** [comment]
Thanks for the feedback! Built this in through 57347e5 and release v1.1.0.

**Comment by turnitclockwise** [comment]
Thank you for this addition, works as requested! 👍 much appreciated!
